WITH TiempoInactividad AS (
    SELECT 
        ASO_IDENTIFICACION, 
        TRUNC(MONTHS_BETWEEN(SYSDATE,ASO_FECHA_CAMBIO_ESTADO_MULT)) AS "Tiempo_Inactividad_Meses", 
        ROW_NUMBER()OVER(PARTITION BY ASO_IDENTIFICACION ORDER BY ASO_FECHA_CREA DESC) AS RN
    FROM GCC_ASOCIADO
)
SELECT
    ASO_IDENTIFICACION AS "CEDULA", 
    "Tiempo_Inactividad_Meses"
FROM TiempoInactividad
WHERE
    RN = 1
    AND ASO_IDENTIFICACION IN ({ids});